WATCHLIST_PATH = "/Users/kelseykerbawy/Desktop/watchlist_test.xlsx"
MARKET = "^RUA"
PERIOD = "2y" # valid periods are 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
INTERVAL = "1d" #valid intervals are 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
IS_CONTINOUSLY_COMPOUNDED = False
SAMPLE_START = '2021-02-01'
SHORTFALL_PERIODS = 20
MIN_BETA = 0.2
MAX_BETA = 1.8
ALLOCATION_METHOD = 'gamma' # valid methods are 'tangency', 'min', and 'gamma'
POSITION_PATH = "/Users/kelseykerbawy/Desktop/position_test.csv"
POSITION_PURCHASE_DATE = "2023-01-01"
SHORTFALL_PATH = "/Users/kelseykerbawy/Desktop/shortfall.csv"
E_PATH = "/Users/kelseykerbawy/Desktop/E.csv"